apiVersion: konflux-ci.dev.konflux-ci.dev/v1alpha1
kind: ExternalAdmissionConfig
metadata:
  labels:
    app.kubernetes.io/name: kueue-external-admission
    app.kubernetes.io/managed-by: kustomize
  name: externaladmissionconfig-sample
spec:
  # TODO(user): Add fields here
